### ISSUE TITLE
How to deal with "error:the following arguments are required: --port, --board"

### ISSUE THREAD

**Issue by Hfut-Lujie** [Andrey1994/brainflow#18]
![QQ20191009-230006](https://user-images.githubusercontent.com/49814550/66493432-a1d65000-eae8-11e9-8acf-aff4286cc860.png)

I'm new to Python with argparse, can someone help me with where to add arguments?

**Comment by Andrey1994** [comment]
you need to provide them, its a standard argparse module, for example for cyton on windows you need to run it as
python brainflow_get_data.py --port COM3 --board 0

**Comment by Andrey1994** [comment]
just run it from command line outside Pycharm\Vscode... whatever you use

**Comment by Andrey1994** [comment]
Also if you have specific board you can just remove argparse and hardcode values directly in python script, also there are SDKs for other languages so you can choose language you like

**Comment by Hfut-Lujie** [comment]
Thank you very much. I'll have a try
