### ISSUE TITLE
native library: DataHandler.dll is not found in jar file

### ISSUE THREAD

**Issue by RkVladimir** [Andrey1994/brainflow#25]
I have error during compilation the project...
Also, inside in jar file this dll  is absent

**Comment by Andrey1994** [comment]
Which jar file do you use? And whats the error in compilation?

**Comment by Andrey1994** [comment]
If you didnt compile it successfully and build jar file by yourself there will be no such library in jar. It will occur if you compile brainflow.

Also you can download jar file from https://github.com/Andrey1994/brainflow/releases 

And will be useful if you provide more info about compilation error

**Comment by RkVladimir** [comment]
Ok.Thanks. Resolved.

**Comment by Andrey1994** [comment]
what was the compilation error?
