### ISSUE TITLE
Neurofeedback calculations: Phase, Coherence, Synchrony, etc.

### ISSUE THREAD

**Issue by ElliotMebane** [Andrey1994/brainflow#28]
Will there be methods useful in Neurofeedback designs, such as Phase, Coherence, Synchrony, etc.? These terms don't always have the same algorithm across different platforms so it might be a challenge to determine what algorithm(s) to include in BrainFlow.

**Comment by Andrey1994** [comment]
Hi!

Right now I dont have plans to implement it inside BrainFlow and I think it can be impelmented in applications/libraries which are focused primary on neurofeedback.

But if there are a lot of users interested in this API I will consider adding it to BrainFlow
