### ISSUE TITLE
AttributeError: 'range' object has no attribute 'remove'

### ISSUE THREAD

**Issue by zubaira123** [Andrey1994/brainflow#8]
self.untrained_chars.remove (self.untrained_chars[rand_index])
AttributeError: 'range' object has no attribute 'remove'

**Comment by Andrey1994** [comment]
This issue should be in brainapps project and not related to brainflow
p300-speller was developd with python2.7 originally and range in python2.7 returns list while in python3 it's iterable object.
But patch which I sent a day ago fix it and moved p300-speller to python3, make sure that you use the latest version it should be fixed
https://github.com/Andrey1994/brainapps/commit/9caceddcd68b36eff307304da9c989e7976b5efc#diff-0aa11cfaf18775f9a776b55acdf0c0ccR74
